[org/gnome/shell/extensions/forge]
auto-split-enabled=true
focus-border-color='rgba(0, 0, 128, 1)'
focus-border-toggle=true
preview-hint-enabled=false
tiling-mode-enabled=true
window-gap-hidden-on-single=false
window-gap-size=uint32 4

[org/gnome/shell/extensions/forge/keybindings]
con-split-horizontal=@as []
con-split-layout-toggle=@as []
con-split-vertical=@as []
con-stacked-layout-toggle=@as []
con-tabbed-layout-toggle=@as []
con-tabbed-showtab-decoration-toggle=@as []
focus-border-toggle=@as []
prefs-tiling-toggle=@as []
window-focus-down=['<Super>j']
window-focus-left=['<Super>h']
window-focus-right=['<Super>l']
window-focus-up=['<Super>k']
window-gap-size-decrease=@as []
window-gap-size-increase=@as []
window-move-down=@as []
window-move-left=@as []
window-move-right=@as []
window-move-up=@as []
window-resize-bottom-decrease=@as []
window-resize-bottom-increase=@as []
window-resize-left-decrease=@as []
window-resize-left-increase=@as []
window-resize-right-decrease=@as []
window-resize-right-increase=@as []
window-resize-top-decrease=@as []
window-resize-top-increase=@as []
window-snap-center=@as []
window-snap-one-third-left=@as []
window-snap-one-third-right=@as []
window-snap-two-third-left=@as []
window-snap-two-third-right=@as []
window-swap-down=['<Super>Down']
window-swap-last-active=@as []
window-swap-left=['<Super>Left']
window-swap-right=['<Super>Right']
window-swap-up=['<Super>Up']
window-toggle-always-float=@as []
window-toggle-float=@as []
workspace-active-tile-toggle=@as []
