#!/bin/bash

set -o errexit
set -o nounset

cd "$(dirname "$(readlink --canonicalize "${BASH_SOURCE[0]}")")"

export PATH="${HOME}/.nix-profile/bin:${PATH}"

SCRIPT_DIRECTORY="${HOME}/.local/bin"
COMPLETION_DIRECTORY="${HOME}/.local/share/bash-completion/completions"
RANGER_PLUGIN_DIRECTORY="${HOME}/.config/ranger/plugins"

home_paths() {
	find software/home/*/ -mindepth 1 -printf '%P\n'
	find scripts -mindepth 1 -maxdepth 1 -printf ".local/bin/%P\n"
	find completions -mindepth 1 -maxdepth 1 -printf ".local/share/bash-completion/completions/%P\n"
}

create_directories() {
	mkdir --parents ~/.go
}

deploy_home_manager() {
	if command -v home-manager >/dev/null; then
		home-manager switch --flake "${PWD}/nix#${USER}" -b backup
		return
	fi

	local activation
	activation="$(nix --extra-experimental-features 'nix-command flakes' build --no-link \
		--print-out-paths "${PWD}/nix#homeConfigurations.${USER}.activationPackage")"
	HOME_MANAGER_BACKUP_EXT=backup "${activation}/activate"
}

remove_stale_links() {
	local root="$1" privileged="${2:-}"
	local relative link

	while read -r relative; do
		link="${root%/}/${relative}"
		if [[ -L ${link} && ! -e ${link} ]]; then
			case "$(readlink "${link}")" in
			.dotfiles/* | */.dotfiles/*) ${privileged} rm "${link}" ;;
			esac
		fi
	done
}

deploy_scripts() {
	mkdir --parents "${SCRIPT_DIRECTORY}" "${COMPLETION_DIRECTORY}"
	stow --target "${SCRIPT_DIRECTORY}" --restow scripts
	stow --target "${COMPLETION_DIRECTORY}" --restow completions
}

deploy_home_packages() {
	mkdir --parents "${RANGER_PLUGIN_DIRECTORY}"
	# shellcheck disable=SC2035 # stow rejects ./*/ as package names
	(cd software/home && stow --target "${HOME}" --no-folding --restow */)
}

deploy_ssh_config() {
	chmod 600 software/home/ssh/.ssh/config
	mkdir --parents "${HOME}/.ssh/config.d"
	chmod 700 "${HOME}/.ssh/config.d"
}

create_directories
deploy_home_manager
home_paths | sort --unique | remove_stale_links "${HOME}"
deploy_scripts
deploy_home_packages
deploy_ssh_config
