#!/bin/bash

set -o errexit
set -o nounset

cd "$(dirname "$(readlink --canonicalize "${BASH_SOURCE[0]}")")"

deploy_home_packages() {
	(cd home && stow --target "${HOME}" --restow -- */)
}

deploy_system_packages() {
	(cd system && sudo stow --target / --no-folding --restow -- */)
}

restart_compose_key_daemon() {
	if systemctl cat keyd.service >/dev/null 2>&1; then
		sudo systemctl restart keyd
	fi
}

deploy_home_packages
deploy_system_packages
restart_compose_key_daemon
