unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi DoubleClick1pane send-keys -X select-word
bind -T copy-mode-vi TripleClick1pane send-keys -X select-line

bind -T copy-mode-vi 'v' send -X begin-selection

bind -T copy-mode-vi 'y' send-keys -X copy-selection

bind -T copy-mode-vi Pageup send-keys -X page-up
bind -T copy-mode-vi NPage send-keys -X page-down

bind -T copy-mode-vi u send-keys -X page-up
bind -T copy-mode-vi d send-keys -X page-down