bind -n M-BSpace run-shell '~/.local/bin/tmux-kill-pane'
bind -n M-r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"
bind -n C-v run-shell '~/.local/bin/tmux-paste'
bind -n User1 if-shell "~/.local/bin/tmux-is-ranger" 'send-keys Q'
