source-file ~/.tmux.conf.d/options.conf
source-file ~/.tmux.conf.d/commands.conf

# Source all binding files
run-shell 'for f in ~/.tmux.conf.d/keybindings/*.conf; do [ -f "$f" ] && tmux source-file "$f"; done'

source-file ~/.tmux.conf.d/appearance.conf

run-shell ~/.tmux/plugins/tmux-fingers/tmux-fingers.tmux
