set preview_images true
set preview_images_method kitty
set show_hidden false

setlocal path=~/remoterepos/google_drive automatically_count_files false
setlocal path=~/remoterepos/google_drive preview_files false

map l enter_dir

map dr ripdrag
map T tab_new
map <c-n> tab_move 1
map <c-p> tab_move -1
map < tab_shift -1
map > tab_shift 1

map <space>D extract
map <space>C compress

map <space>pf fzf_project_files
map <space>pd fzf_project_dirs
map <space>pr fzf_project_rg
map <space>df fzf_dir_files
map <space>dd fzf_dir_dirs
map <space>dr fzf_dir_rg
map <space>z  fzf_z

unmap yp
unmap yd
unmap yn
unmap y.
map <space>yp yank path
map <space>yd yank dir
map <space>yn yank name
map <space>y. yank name_without_extension

map v mark_files toggle=True
map * mark_files all=True toggle=True
