mime ^image, has loupe, X, flag f = loupe -- "$1"

mime ^audio, has vlc, X, flag f = vlc -- "$@"

ext pdf, has papers, X, flag f = papers -- "$1"
ext pdf, has xournalpp, X, flag f, label annotate = xournalpp -- "$1"

ext xopp, has xournalpp, X, flag f = xournalpp -- "$1"

mime ^application/json = $EDITOR -- "$1"
ext json = $EDITOR -- "$1"
mime ^application/json, has jq, label jq = jq . "$1" | ${PAGER:-less}
ext json, has jq, label jq = jq . "$1" | ${PAGER:-less}

mime ^text, label editor = $EDITOR -- "$1"
