mime ^image, has feh, X, flag f = feh -- "$1"
mime ^image, has loupe, X, flag f = loupe -- "$1"
mime ^image, has eog, X, flag f = eog -- "$1"

# Audio files
mime ^audio, has vlc,    X, flag f = vlc -- "$@"
mime ^audio, has mpv,    X, flag f = mpv -- "$@"
mime ^audio, has ffplay, X, flag f = ffplay -- "$@"
ext wav,     has aplay,  terminal  = aplay -- "$@"

ext pdf, has zathura, X, flag f = zathura -- "$1"
ext pdf, has evince, X, flag f = evince -- "$1"
ext pdf, has okular, X, flag f = okular -- "$1"
ext pdf, has xpdf, X, flag f = xpdf -- "$1"

mime ^application/json, has jq = jq . "$1" | ${PAGER:-less}
ext json, has jq = jq . "$1" | ${PAGER:-less}
mime ^application/json = $EDITOR -- "$1"
ext json = $EDITOR -- "$1"

mime ^text, label editor = $EDITOR -- "$1"
