[org/gnome/mutter]
auto-maximize=false
dynamic-workspaces=false

[org/gnome/desktop/wm/preferences]
num-workspaces=5

[org/gnome/desktop/input-sources]
sources=[('xkb', 'us+altgr-intl')]

[org/gnome/desktop/peripherals/touchpad]
natural-scroll=false

[org/gnome/desktop/background]
show-desktop-icons=false
