#!/bin/bash

[[ -z "${1}" ]] && echo "Missing argument" && exit 1

pandoc \
    --variable mainfont="DejaVu Sans" \
    --pdf-engine=typst \
    --highlight-style zenburn \
	"${1}" --output "${1//md/pdf}"

