#!/usr/bin/env bash

! command -v fzf >&/dev/null && echo "fzf not installed" && exit 1

file=$(rg --color=always --line-number --no-heading --smart-case "${*:-}" |
  fzf --ansi \
      --delimiter : \
      --preview 'fzf-preview {1} {2}' \
      --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
			)

[[ -z "${file}" ]] && echo "No file selected" && exit 0

path=${file%%:*}
line=${file#*:}
line=${line%%:*}

echo "vi ${path} +${line}" >> ~/.bash_history

vi "${path}" "+${line}"
