set-option -g mouse on

set-option -g base-index 1
set-option -w -g pane-base-index 1

set-option -w -g mode-keys vi

set-option -g history-limit 20000

run-shell '[ -x "$HOME/.nix-profile/bin/bash" ] && tmux set-option -g default-shell "$HOME/.nix-profile/bin/bash"; true'

set-option -g status-right ''
set-option -g status-left-length 40

# Renumber windows at each change
set-option -g renumber-windows on

# Window name = current directory instead of running command
set-option -w -g automatic-rename-format '#{b:pane_current_path}'

# Focus event support
set-option -g focus-events on

# No delay typping a key, avoid trouble while using vim
set-option -s -g escape-time 0

# Allow external program such as vim to display picture
set-option -g -q allow-passthrough on
set-option -g visual-activity off

set -s set-clipboard on
set -as terminal-features ',alacritty:extkeys:clipboard'
set -s extended-keys on
set -s extended-keys-format csi-u

# Alt+[ re-encodé en \e[777~ par alacritty, déclaré comme user-key pour tmux
set -s user-keys[0] "\e[777~"

# Ctrl+Shift+Q ré-encodé en \e[778~ par alacritty, déclaré comme user-key pour tmux
set -s user-keys[1] "\e[778~"
