bind -n "M-<" swap-window -dt -1
bind -n "M->" swap-window -dt +1
bind -n "M-(" switch-client -p
bind -n "M-)" switch-client -n
bind -n "M-:" command-prompt
bind -n User0 copy-mode
bind -n "M-\?" list-keys
bind -n 'M-!' break-pane
bind -n 'M- ' choose-tree -sZ
bind -n M-, command-prompt -I "#W" "rename-window '%%'"
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-= choose-buffer
bind -n M-c new-window -a
bind -n M-d detach
bind -n M-n next-window
bind -n M-p previous-window
bind -n M-z resize-pane -Z

bind -n M-PageUp previous-window
bind -n M-PageDown next-window

bind -n M-o last-window
bind -n M-O switch-client -l
bind -n 'C-M-o' killp -a
bind -n M-BSpace run-shell '~/.local/bin/tmux-kill-pane'

bind -n "M-down" resize-pane -D
bind -n "M-left" resize-pane -L
bind -n "M-right" resize-pane -R
bind -n "M-up" resize-pane -U

bind -n M-R respawn-pane -k
bind -n M-r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

bind -n 'M-J' swap-pane -D
bind -n 'M-K' swap-pane -U

bind -n 'M-v' split-window
bind -n 'M-V' split-window -f
bind -n 'M-t' split-window -h
bind -n 'M-T' split-window -fh

bind -n C-v run-shell '~/.local/bin/tmux-paste'

bind -n User1 if-shell "~/.local/bin/tmux-is-ranger" 'send-keys Q'
